# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YourAppTargetName' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YourApp

  # Marketing
  pod 'Braze-iOS-SDK' # Braze (formerly Appboy) for marketing automation
  pod 'Branch' # Branch for deep linking and attribution

  # Analytics
  pod 'Firebase/Analytics' # Firebase for analytics and other Google services
  pod 'Mixpanel' # Mixpanel for advanced analytics
  pod 'Amplitude-iOS', '~> 8.0' # Amplitude for event tracking

  # Advertising
  pod 'Google-Mobile-Ads-SDK' # Google Mobile Ads for monetization
  pod 'FacebookAdsSDK' # Facebook Ads SDK for advertising
  pod 'MoPub-SDK' # MoPub for ad serving

  # Additional utilities that might be used alongside marketing and advertising
  pod 'Alamofire', '~> 5.2' # Networking library for making HTTP requests
  pod 'SDWebImage' # Asynchronous image loading

  # Other dependencies often used in conjunction with marketing and advertising
  pod 'AppsFlyerFramework' # AppsFlyer for app tracking and attribution
  pod 'Adjust' # Adjust for attribution and analytics
  pod 'Flurry-iOS-SDK/FlurrySDK' # Flurry for analytics and ads

  # Ensure you include 'use_frameworks!' if one of your pods uses Swift
  # ...

end

# Add post-install hooks if necessary, for configuring specific pod settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0' # Set a global Swift version for all pods
      # Other configurations
    end
  end
end
