name: Version Bump Check

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Test for changed files
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            src/
            examples/
            scripts/
            package.json
            README.md
            pnpm-lock.yaml

      - name: Check if package.json version has been modified
        shell: bash
        if: ${{ github.base_ref == 'main' && steps.changed-files.outputs.any_changed == 'true' }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          if PAGER= git diff --unified=0 origin/main package.json | grep '\+  "version":' > /dev/null; then
            echo "✅ Version has been bumped successfully";
          else
            echo "❌ Error: Files have been modified but package.json version has not been bumped.";
            echo ""
            echo "Modified files:";
            echo "$ALL_CHANGED_FILES";
            echo ""
            echo "Please bump the version in package.json using one of:";
            echo "  - npm version patch (for bug fixes)";
            echo "  - npm version minor (for new features)";
            echo "  - npm version major (for breaking changes)";
            exit 1;
          fi
